version: '3.9'
services:
  db:
    image: "postgres:14.5-alpine"
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  app:
    build: ./
    command: ./app
    ports:
      - "8080:8080"
    depends_on:
      - db